# Site settings
title: June Blog
SEOTitle: 徐子昂的博客 | Github.io
header-img: img/post-bg-desk.jpg
email: 3439394104@qq.com
description: "Who Changes? Who Benifits!"
keyword: "徐子昂的博客, Ziang, Python, Bio, Gaming"
url: "https://June6699.github.io"
baseurl: ""
github_repo: "https://github.com/June6699/June6699.github.io.git"

# Sidebar settings
sidebar: true
sidebar-about-description: "此子心性甚佳"
sidebar-avatar: /img/底特律·变包.png

# SNS settings
RSS: false
disqus_username: June6699
weibo_username:     
zhihu_username:     
github_username:    
facebook_username:  
jianshu_username:	

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true

# Gems
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# 评论系统
Disqus（https://disqus.com/）
disqus_username: June6699

# Gitalk
gitalk:
  enable: true
  clientID: Ov23lip1sLnFPYK622n1
  clientSecret: 66b4d7a3fa6cf24bb721f85072a93fddc0d80229
  repo: June6699.github.io
  owner: June6699
  admin: June6699
  distractionFreeMode: true

# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: 6a0eceeee843ef6235b91843cc1a936e

# Google Analytics
ga_track_id: 'G-S7DXV0QV58'
ga_domain: auto

# Featured Tags
featured-tags: true
featured-condition-size: 1

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Friends
friends: [
    {
        title: "WY",
        href: "http://zhengwuyang.com"
    },{
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]